Include machine info and clang/llvm version info in the .ll files generated by c2ll.

diff --git a/tools/c2ll b/tools/c2ll
--- a/tools/c2ll
+++ b/tools/c2ll
@@ -1,4 +1,10 @@
 #! /usr/bin/env bash
 BASE=`basename $1 .c`
-clang -O0 -emit-llvm -S $1
-mv $BASE.s $BASE.ll
+clang -S -emit-llvm $1
+if [ $? -ne 0 ]; then
+    echo "c2ll failed"
+    exit 1
+fi
+printf "BEGIN C2LL PROFILE\n$ date\n%s\n$ uname -a\n%s\n$ clang --version\n%s\n$ opt --version\n%s\n$ pwd\n%s\n$ clang -S -emit-llvm $1\n...\n$ sha256sum $BASE.s\n%s\nEND C2LL PROFILE\n" "`date`" "`uname -a`" "`clang --version`" "`opt --version`" "`pwd`" "`sha256sum $BASE.s`" | sed 's/^/; /' > $BASE.ll
+cat $BASE.s >> $BASE.ll
+rm -f $BASE.s
